# Schema for the configuration files of the CRAIN Citybook theme.
crain_citybook.settings:
  type: theme_settings
  label: 'CRAIN Citybook settings'
  mapping:
    font_size:
      type: integer
      label: Font size
